### ISSUE TITLE
xpub/xpriv support with seed

### ISSUE THREAD

**Issue by aayanl** [ZencashOfficial/zencashjs#1]
hacking on this rn, just opening an issue

**Comment by bityogi** [comment]
We are trying to sign ZenCash transactions with extended private keys, and it seems like it doesn't support it.

Getting the error:

```
Underlying error: private key length is invalid
```

But as per [this website](https://iancoleman.io/bip39/#english), we know we're using the correct private key for that address on that index.

Can you confirm if this error is on our end or if this library does not support extended pub/priv keys ?

**Comment by bityogi** [comment]
Nevermind, 

The library does support xpub/xpriv keys.

What I was doing was deriving the private-key from extended-private-key using the bip32 library:

`const wifKey = t.derivePath(derivedIndex).toWIF();`

and then sending this `wifKey` as the private-key to 

`zencashjs.transaction.signTx(tx, i, wifKey);`

However, it seems I needed to convert this WIF key like so:

`const privateKey = zencashjs.address.WIFToPrivKey(wifKey);`

and then send this privateKey to the zencashjs `signTx` method.
