### ISSUE TITLE
Configuration for ZENCash Coin

### ISSUE THREAD

**Issue by lannuo** [ZencashOfficial/zencashjs#15]
module.exports = {
  mainnet: {
    messagePrefix: 'ZENCash main net',
    bip32: {
      public: '0488b21e',
      private: '0488ade4'
    },
    pubKeyHash: '2089',
    scriptHash: '2096',
    zcPaymentAddressHash: '169a', // Private z-address
    zcSpendingKeyHash: 'ab36', // Spending key
    wif: '80'
  },
  testnet: {
    wif: 'ef',
    pubKeyHash: '2098',
    scriptHash: '2092',
    zcPaymentAddressHash: '16b6',
    zcSpendingKeyHash: 'ac08'
  }
};

What's the role of "bip32", "pubKeyHash"," scriptHash"," zcPaymentAddressHash"," zcSpendingKeyHash"," wif" ?
 
Where is the configuration?

**Comment by zennermac** [comment]
For clarity, the best place to seek help with configuration etc is our public Discord server

https://discordapp.com/invite/Hu5mQxR
