### ISSUE TITLE
Err: Code:-25

### ISSUE THREAD

**Issue by 317482454** [ZencashOfficial/zencashjs#19]
I don't know why this problem occurs.
Is it because of the lack of fee?If yes, I did not see where to add the fee in the tutorial.

```javascript
                const bip115BlockHeight = 142091
                const bip115BlockHash = '00000001cf4e27ce1dd8028408ed0a48edd445ba388170c9468ba0d42fff3052'
                let transaction = zencashjs.transaction.createRawTx(
                    utxos,
                    [{ address: data.toAddr, satoshis: parseInt(data.sum) }],
                    bip115BlockHeight,
                    bip115BlockHash
                )
                let prv = this.privateKey(phrase)
                for (let i = 0; i < transaction.ins.length; i += 1) {
                    transaction = zencashjs.transaction.signTx(transaction, i, prv, true)
                }
                let tx= zencashjs.transaction.serializeTx(transaction)
```
hex
`01000000018796da41cc54e918e62bb660c01e992492e3bfa4a56317961f5483e022d02165010000006a47304402200def4b7a9dab41b10de8b9ec1736edd729a4c7994fcf48a7d963c87050e148e0022022012750838cbac3552b71c736072e16a642cc75bbbcb0b9fddf79f78945911c012102b51117ca8b6b0de630f42763a2be1b1ce7fe322ae750ee8d4eaaaf65ed7aeb5affffffff0140420f00000000003f76a9147bfb6527e7e3f95cf3b009068483176b86de130d88ac205230ff2fd4a08b46c9708138ba45d4ed480aed088402d81dce274ecf01000000030b2b02b400000000 `

**Comment by psyraxaus** [comment]
Hi, 
when you were creating the raw transaction, did you specify a change address for any zen left over  if you did not use all the available zen?

**Comment by psyraxaus** [comment]
A previous example of this error when using the zend daemon directly
When you are not specifying a "change" address in your outputs, this will result in an error in the debug log like 
`2018-12-28 03:08:32 ERROR: AcceptToMemoryPool: absurdly high fees <mytx>, 4990000 > 220000`

In that example I had an UXTO with 0.05 and was trying to send 0.0001 back to itself, but what happened because I did not specify that 0.0498 zen should go to a change address the error above was thrown.

So by changing the createrawtransaction command to the following
` zen-cli createrawtransaction "[{\"txid\":\"5308396efe994b039183b93eae95d1a31984fbf8bf48bb44a5883a2ef1441be1\",\"vout\":0}]" "{\"znckPzd4qY1Cvx9cXm66MTrqNMPci7aGEVX\":0.0001,\"znhZpM1EhLMXxYQuYMZALV6x7kXtrXkGi81\":0.0498}"`

it then created the necessary "change" address and the transaction was successful, and was able to be sent

**Comment by 317482454** [comment]
Sorry, I don't understand a bit, how to do this step in zencashjs

**Comment by psyraxaus** [comment]
Currently your code is only creating a single vOut
`                    [{ address: data.toAddr, satoshis: parseInt(data.sum) }],`
I decoded your raw transaction and could see that you are trying to send 0.01 zen to zncPUGG6v3kdPUPPyKZKLJ2cLycgtSFm6vM, and using your previous transaction the address you are trying to send from has 2.94084001 zen in it.

Without specifying the fee or the change address, you are trying to send a transaction for the 0.01 to the address and fee of 2.93084001 zen.  This is being rejected by the network as being a ridiculously high fee.

I can see that the README example does not account for the fee or the change address.

You will need to add some additional code to your example to add a change address vOut minus the fee.  That way you would have the first vOut sending 0.01 zen to zncPUGG6v3kdPUPPyKZKLJ2cLycgtSFm6vM, and 2.92984001 zen to a change address, and 0.0001 zen for a fee (if you choose to use that as the fee).

I am not 100% sure of the syntax, but something like this
`                let transaction = zencashjs.transaction.createRawTx(
                    utxos,
                    [{ address: data.toAddr, satoshis: parseInt(data.sum) },{ address: data.fromAddr, satoshis: currentBal - parseInt(data.sum) - 0.0001 }],
                    bip115BlockHeight,
                    bip115BlockHash
                )`

I am not really a js coder but hopefully my example above will be able to help you

**Comment by 317482454** [comment]
Thank you for your help, I think, we need to wait for the developer's reply.
This is the addition of the change address, but it still seems useless, I reserved a fee of 0.001。
`01000000018796da41cc54e918e62bb660c01e992492e3bfa4a56317961f5483e022d02165000000006a47304402200f69d393239c08c1b98dce4d54127adde1510a5712d3070420b2319490c424eb02204edd82402d29bddc4716741a9cb407cb087b1a3a16ead4d396bba180d820203c012102b51117ca8b6b0de630f42763a2be1b1ce7fe322ae750ee8d4eaaaf65ed7aeb5affffffff0240420f00000000003f76a9147bfb6527e7e3f95cf3b009068483176b86de130d88ac205230ff2fd4a08b46c9708138ba45d4ed480aed088402d81dce274ecf01000000030b2b02b4c1947611000000003f76a9147655255f2236acf50c7d724c9dbf8d97f1b7ac3b88ac205230ff2fd4a08b46c9708138ba45d4ed480aed088402d81dce274ecf01000000030b2b02b400000000 `

**Comment by psyraxaus** [comment]
So this is the error now that I am seeing when trying to broadcast the raw transaction through my block explorer

>  An error occured:
> 18: bad-txns-inputs-spent. Code:-26

Looks like the incorrect UXTO was used

**Comment by 317482454** [comment]
Thank you, I have solved it.
