### ISSUE TITLE
Code:-26 error with multi-sig transaction

### ISSUE THREAD

**Issue by vietvu-nguyen** [ZencashOfficial/zencashjs#26]
Hi, I am trying to make a multi-sig transaction, but got a Code:-26 error.
`16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26 `

Could someone help me with this? thank you in advance.

Codesandbox: https://codesandbox.io/embed/x3jklr98zp-zen-3-remote-ms-jp27m

**Comment by cronicc** [comment]
Is this still an issue after our conversation on Discord?

From Discord:
```
This usually means the signature is wrong or incomplete, signature order matters with P2SH addresses. Private keys provided to spend from a P2SH address have to be given in the same order (skipping keys is okay when m < n, but still in the same order) as given when the P2SH address was generated.
```

**Comment by vietvu-nguyen** [comment]
Thank you. I was able to resolve it.
