### ISSUE TITLE
serializeTx and deserializeTx misses prevScriptPubKey from inputs

### ISSUE THREAD

**Issue by jinghanxu-coinbase** [ZencashOfficial/zencashjs#27]
Been trying to use this lib to for our transaction flow
Things work if we do
1. createRawTx
2. signTx

It breaks if we do 
1. createRawTx
2. serializeTx
3. deserializeTx
4. signTx

I think it's because serializeTx is leaving out the prevScriptPubKey

**Comment by cronicc** [comment]
Thanks for reporting the issue, we're looking into it and are working on a solution.

**Comment by cronicc** [comment]
Functionality to include `prevScriptPubKey` in serialization added in https://github.com/ZencashOfficial/zencashjs/tree/v1.2.2.
