### ISSUE TITLE
TypeError: unsupported input type for privateKey

### ISSUE THREAD

**Issue by JiniHendrix** [ZencashOfficial/zencashjs#6]
Getting this error when using zencashjs.zaddress.zSecretKeyToPayingKey(secretKey).

The error is coming from the libsodium-wrappers-sumo dependency.

I'm using the example secretKey and it's still not working and I"ve no idea why. I've tested the usage in fresh projects as well as the npm browser tester and it works properly.

the code is no different from the example besides hardcoding the example secret key.

`
        const secretKey = '0c10a61a669bc4a51000c4c74ff58c151912889891089f7bae5e4994a73af7a8';
        
        const spendingKey = zencashjs.zaddress.zSecretKeyToSpendingKey(secretKey);
        
        const payingKey = zencashjs.zaddress.zSecretKeyToPayingKey(secretKey);
        
        const transmissionKey = zencashjs.zaddress.zSecretKeyToTransmissionKey(secretKey);
        
        const zAddress = zencashjs.zaddress.mkZAddress(payingKey, transmissionKey);`

**Comment by kendricktan** [comment]
Interesting. What node and npm version are you running?

**Comment by JiniHendrix** [comment]
Node v8.9.4
npm 5.6.0

I tried installing it and trying the example in a new, separate project and it worked fine. strange stuff.
